# 头部菜单，title: link
menu:
  关于我: /whoami
  Github: https://github.com/Billin9
  分类: /categories
  归档: /archives
  标签: /tags

# 是否显示目录
TOC: false

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3:
  - http://www.170mv.com/kw/other.web.ri01.sycdn.kuwo.cn/resource/n1/73/40/4073043717.mp3 # 光年之外
  - http://www.170mv.com/kw/other.web.ri01.sycdn.kuwo.cn/resource/n2/83/80/2001880351.mp3 # 空心-冯提莫
  - http://www.170mv.com/kw/other.web.nc01.sycdn.kuwo.cn/resource/n2/11/71/1946862123.mp3 # 过客-阿涵
  - http://www.170mv.com/kw/other.web.rh01.sycdn.kuwo.cn/resource/n3/4/62/1367045916.mp3 # 长腿叔叔
  - http://www.170mv.com/kw/other.web.nf01.sycdn.kuwo.cn/resource/n2/80/22/3777994537.mp3 # In the eyes
  - https://link.hhtjim.com/kg/4B5ABE45B12731446EA10C83792C118A.mp3 # 走马-莲莉rei
  - http://www.170mv.com/kw/other.web.rg01.sycdn.kuwo.cn/resource/n2/33/99/2947872486.mp3 # 风筝误
  - http://www.170mv.com/kw/other.web.ri01.sycdn.kuwo.cn/resource/n3/87/27/83621971.mp3 # Psycho (Pt.2)
  - https://link.hhtjim.com/163/513360721.mp3 # 云烟成雨
  - http://www.170mv.com/kw/other.web.nf01.sycdn.kuwo.cn/resource/n1/0/0/1867614926.mp3 # 锈琴
  - http://www.170mv.com/kw/other.web.rt01.sycdn.kuwo.cn/resource/n2/46/77/2638665343.mp3 # Wonderful U (Demo)
  - https://link.hhtjim.com/kg/08422715EC7884A539D995F41409E498.mp3 # 化身孤岛的鲸-兔裹煎蛋卷
  - https://link.hhtjim.com/kw/40891539.mp3 # 烟火里的尘埃-郁欢
  - http://www.170mv.com/kw/other.web.nf01.sycdn.kuwo.cn/resource/n1/24/0/3021515241.mp3 # 那个人

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: 'http://img.dosec.cn/3840x2160_alita-battle-angel-movie-uhdpaper.com-4K-20.jpg' # /img/welcome-cover.jpg

# 默认文章封面图
cover: 'http://img.dosec.cn/1680x1050_Alita-Battle-Angel-2019.jpg' # /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
    # 是否自动展开评论框
    autoExpand: false
    # 应用编号
    clientID: 'ebe7b513e0d4be54826d'
    # 应用秘钥
    clientSecret: 'b6b49c54ad8111f3394f929526324f976430549e'
    # issue仓库名
    repo: 'gitalk'
    # Github名
    owner: 'Billin9'
    # Github名
    admin: ['Billin9']
    # Ensure uniqueness and length less than 50
    id: location.pathname
    # Facebook-like distraction free mode
    distractionFreeMode: false

# 网站关键字
keywords: Python, Go, Shell, ansible, jenkins, devops

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-137987842-1

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
